apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpu-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: gpu-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpu-scheduler-as-volume-scheduler
subjects:
- kind: ServiceAccount
  name: gpu-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-scheduler
  namespace: kube-system
  labels:
    component: gpu-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      component: gpu-scheduler
  template:
    metadata:
      labels:
        component: gpu-scheduler
    spec:
      serviceAccountName: gpu-scheduler
      priorityClassName: system-cluster-critical
      containers:
      - name: gpu-scheduler
        image: registry.k8s.io/kube-scheduler:v1.26.0
        imagePullPolicy: IfNotPresent
        command:
        - kube-scheduler
        - --leader-elect=false
        - --scheduler-name=gpu-scheduler
        - --config=/etc/kubernetes/gpu-scheduler-config.yaml
        volumeMounts:
        - name: gpu-scheduler-config
          mountPath: /etc/kubernetes
      volumes:
      - name: gpu-scheduler-config
        configMap:
          name: gpu-scheduler-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-scheduler-config
  namespace: kube-system
data:
  gpu-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: gpu-scheduler
      plugins:
        score:
          enabled:
          - name: NodeResourcesBalancedAllocation
            weight: 2
          - name: NodeResourcesFit
            weight: 3
        filter:
          enabled:
          - name: NodeResourcesFit
      pluginConfig:
      - name: NodeResourcesFit
        args:
          apiVersion: kubescheduler.config.k8s.io/v1
          kind: NodeResourcesFitArgs
          scoringStrategy:
            resources:
            - name: nvidia.com/gpu
              weight: 10
