apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: drift-ml-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-tls
  namespace: drift-ml-data
spec:
  dnsNames:
  - "*.kafka-broker-headless.drift-ml-data.svc.cluster.local"
  - "*.kafka-controller-headless.drift-ml-data.svc.cluster.local"
  - "kafka-broker-external.drift-ml.com"
  secretName: kafka-tls
  issuerRef:
    name: drift-ml-issuer
    kind: ClusterIssuer
